### ISSUE TITLE
Prevent dashes around long names from breaking to new lines

### ISSUE THREAD

**Issue by marykatefain** [Uptwinkles/dashboard#19]

**Comment by alexgleason** [comment]
For one it might be helpful to set `white-space: nowrap;` on the parent element. It'll treat the whole piece of text, including words, as a single word and therefore won't wrap on spaces.

If you're okay with first/last names wrapping but you don't want the hyphens to wrap, you can do this `—&nbsp;{{ name }}&nbsp;—`

**Comment by marykatefain** [comment]
This worked, thank you.

**Comment by alexgleason** [comment]
Looks fine, but there's still a vertical scrollbar on our 19" screen for some reason

**Comment by marykatefain** [comment]
Weird... thanks. There's probably just some small margin or something down there pushing it over.
